IfColor 16,16,"551C09",2 Then
KeyDown "Ctrl", 1
KeyDown "F1", 1
Delay 56
KeyUp "F1", 1
KeyUp "Ctrl", 1
Else
IfColor 16,16,"AA3913",2 Then
KeyDown "Ctrl", 1
KeyDown "F2", 1
Delay 56
KeyUp "F2", 1
KeyUp "Ctrl", 1
Else
IfColor 16,16,"551C",2 Then
KeyDown "Ctrl", 1
KeyDown "F3", 1
Delay 56
KeyUp "F3", 1
KeyUp "Ctrl", 1
Else
IfColor 16,16,"557126",2 Then
KeyDown "Ctrl", 1
KeyDown "F4", 1
Delay 56
KeyUp "F4", 1
KeyUp "Ctrl", 1
Else
IfColor 16,16,"AA8E2F",2 Then
KeyDown "Ctrl", 1
KeyDown "F5", 1
Delay 56
KeyUp "F5", 1
KeyUp "Ctrl", 1
Else
IfColor 16,16,"AA39",2 Then
KeyDown "Ctrl", 1
KeyDown "F6", 1
Delay 56
KeyUp "F6", 1
KeyUp "Ctrl", 1
Else
IfColor 16,16,"55C642",2 Then
KeyDown "Ctrl", 1
KeyDown "F7", 1
Delay 56
KeyUp "F7", 1
KeyUp "Ctrl", 1
Else
IfColor 16, 16, "AAE34C", 2 Then
KeyDown "Ctrl", 1
KeyDown "F8", 1
Delay 56
KeyUp "F8", 1
KeyUp "Ctrl", 1
Else
IfColor 16, 16, "55", 2 Then
KeyDown "Ctrl", 1
KeyDown "F9", 1
Delay 56
KeyUp "F9", 1
KeyUp "Ctrl", 1
Else
IfColor 16, 16, "551C5E", 2 Then
KeyDown "Ctrl", 1
KeyDown "F10", 1
Delay 56
KeyUp "F10", 1
KeyUp "Ctrl", 1
Else
IfColor 16, 16, "AA3968", 0 Then
KeyDown "Ctrl", 1
KeyDown "F11", 1
Delay 56
KeyUp "F11", 1
KeyUp "Ctrl", 1
End If
End If
End If
End If
End If
End If
End If
End If
End If
End If
End If
