C_Timer.After(0.4, function()
    SetCVar('cameraDistanceMaxZoomFactor', 3.34)
    SetCVar('nameplateMaxDistance', 41)
end)
C_Timer.After(1.4, function()
    SetCVar('cameraDistanceMaxZoomFactor', 3.34)
    SetCVar('nameplateMaxDistance', 41)
end)
