syntax on
set background=dark

set number
set autoindent
set hlsearch

setlocal tabstop=8 expandtab shiftwidth=4 softtabstop=4

set backspace=indent,eol,start

autocmd Filetype c setlocal tabstop=4 expandtab shiftwidth=2 softtabstop=2 tw=120
autocmd Filetype cpp setlocal tabstop=4 expandtab shiftwidth=2 softtabstop=2 tw=120
autocmd Filetype python setlocal tabstop=4 expandtab shiftwidth=2 softtabstop=2 tw=120
" autocmd Filetype php setlocal tabstop=8 expandtab shiftwidth=4 softtabstop=4
" autocmd Filetype sh setlocal tabstop=8 expandtab shiftwidth=4 softtabstop=4
autocmd Filetype gitcommit setlocal tw=72
