if [ -f ~/.lmintrc ]; then
    . ~/.lmintrc
fi

if [ -d /Users/jki14/apps/gradle/4.9/bin ]; then
    export PATH=$PATH:/Users/jki14/apps/gradle/4.9/bin
fi

export LC_ALL=en_US.UTF-8

export LSCOLORS=ExFxCxDxBxegedabagacad
alias ll='ls -alG'

export PS1='\[\033[01;32m\]\u@\h\[\033[00m\] \[\033[01;34m\]\w \$\[\033[00m\] '

alias google-chrome='open -a "Google Chrome"'
alias sublime='open -a "Sublime Text"'

# vi: set syntax=sh:
