# Kiro CLI pre block. Keep at the top of this file.
[[ -f "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.pre.zsh" ]] && builtin source "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.pre.zsh"

if [ -f ~/.lmintrc ]; then
    . ~/.lmintrc
fi

if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

export LC_ALL=en_US.UTF-8

export LSCOLORS=ExFxCxDxBxegedabagacad
alias ll='ls -alG'

export PS1='%F{113}%n@%m%f %F{74}%1~%f %# '

alias google-chrome='open -a "Google Chrome"'
alias sublime='open -a "Sublime Text"'

# vi: set syntax=sh:


# Kiro CLI post block. Keep at the bottom of this file.
[[ -f "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.post.zsh" ]] && builtin source "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.post.zsh"
